backend:
  name: github
  repo: uscensusbureau/the-opportunity-project
  base_url: https://opportunity.census.gov/
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: main